return {
    -- {
    --     "sphamba/smear-cursor.nvim",
    --     event = "VeryLazy",
    --     opts = {
    --         -- Smear color. Default is your cursor's highlight group.
    --         -- cursor_color = "#bb9af7", -- Optional: matching Tokyonight purple
    --
    --         -- Stiffness of the "spring" (0.1 to 1).
    --         -- Higher = faster/snappier, Lower = more "liquid".
    --         stiffness = 0.6,
    --
    --         -- Stiffness of the tail.
    --         trailing_stiffness = 0.3,
    --
    --         -- Stop the animation when moving less than this distance.
    --         distance_stop_animating = 0.1,
    --
    --         -- Set to true if you want the smear to show when switching windows.
    --         smear_between_buffers = true,
    --     },
    -- },
}
